[package]
name = "clarity-repl"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
lazy_static = "1.4.0"
regex = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.47"
sha2 = "0.8.1"
termion = "1.5.5"
rustyline = "6.1.2"